name: easyparking
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  qr_mobile_vision: ^0.3.1
  google_maps_flutter: ^0.5.21+15
  json_serializable: ^2.0.2
  flutter_secure_storage: ^3.3.1+1
  provider: ^3.1.0
  font_awesome_flutter: ^8.5.0
  photo_view: ^0.9.1
  curved_navigation_bar: ^0.3.1
  bottom_navy_bar: ^5.3.2
  transparent_image: ^1.0.0
  zoom_widget: ^0.1.3
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  firebase_messaging: ^6.0.12
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  fluttie: ^0.5.0
  shimmer: ^1.0.1
  matrix_gesture_detector: ^0.1.0
  geocoder: ^0.2.1 
  location: ^2.3.5
  great_circle_distance: ^1.0.1
  flutter_bloc: ^0.18.3
  equatable: ^0.2.6
  firebase_database: ^3.1.1
  flutter_polyline_points: ^0.1.0
  cloud_firestore: ^0.13.4


# Add the following three lines
dev_dependencies:
  pedantic: ^1.4.0
  build_runner: ^1.2.7
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  image_path: "assets/logo_apk.png" 
  android: true
  ios: true
  adaptive_icon_background: "#212121"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/
    - data/
    - assets/
    - assets/animations/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
